### ISSUE TITLE
init method should not call initialize

### ISSUE THREAD

**Issue by sdsykes** [EddyBorja/MLPAutoCompleteTextField#75]
If you call init, for instance by using

    [MLPAutoCompleteTextField new]

then because init calls initWithFrame (with CGRectZero) then it means initialize will be called twice.

This doesn't matter until the MLPAutoCompleteTextField instance is deallocated, at which moment your app will crash with a "deallocation while key value observers still registered" exception.

**Comment by csknns** [comment]
When subclassing, you should override your superclass designated initializer and call [super (designated initializer)]. If you have secondary initializers when they should call the designated initializer on self. The one exception is when the super class conforms to NSCoding and the subclass is implementing the ```- initWithCoder:``` when should call ```[super initWithCoder:coder]``` instead of [super (designated initializer)].

In this case i would call ```[self initWithFrame:CGRectZero]``` instead of ```[super init]``` in the ```- init``` method or I would remove the ```- init``` from the MLPAutoCompleteTextField.

**Comment by sdsykes** [comment]
Agree.
